apiVersion: apps/v1
kind: Deployment
metadata:
  name: orderview
  labels:
    app: orderview
spec:
  replicas: 1
  selector:
    matchLabels:
      app: orderview
  template:
    metadata:
      labels:
        app: orderview
    spec:
      containers:
        - name: orderview
          image: hjo0045/orderview:v230216
          ports:
            - containerPort: 8080
          readinessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 30
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 10
          livenessProbe:
            httpGet:
              path: '/actuator/health'
              port: 8080
            initialDelaySeconds: 120
            timeoutSeconds: 2
            periodSeconds: 5
            failureThreshold: 5
